name: clang-format

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: npm install
      - name: check clang-format
        run: |
          git config clangFormat.binary node_modules/.bin/clang-format
          git config clangFormat.style file
          npx check-clang-format
