name: Test Website Builds

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-website:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: npx envinfo
      - name: Build and Deploy
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        working-directory: ./website
        run: |
          npm install
          npx gatsby build --prefix-paths
