name: Build and Deploy the Website

on:
  push:
    branches: [ main ]

permissions:
  contents: write # Pushes to `gh-pages` branch

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false
      - run: npx envinfo
      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          USER: gatsby-deploy-bot <support+actions@github.com>
          NODE_OPTIONS: --openssl-legacy-provider
        working-directory: ./website
        run: |
          npm install
          npx gatsby build --prefix-paths
          npx gh-pages -d public -r https://git:${TOKEN}@github.com/${REPO}.git -u "${USER}"
